SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
LEFT_PADDLE_POSITION = (-1*(SCREEN_WIDTH // 2 - 50), 0)
RIGHT_PADDLE_POSITION = ((SCREEN_WIDTH // 2 - 50), 0)
X_BOUNDARY = (SCREEN_WIDTH // 2) - 10
Y_BOUNDARY = (SCREEN_HEIGHT // 2) - 10